### ISSUE TITLE
Unable to compile for target simrobot

### ISSUE THREAD

**Issue by rkost** [HULKs/HULKsCodeRelease#2]
**From #1 by @heodel:**

When I compile the SimRobot , I encountered an error in the cpp file , which is in the Motion section.
I compiled it four times and used the following instructions:

nao /scripts/compile -t simrobot -b <BUILD_TYPE>

The type I used as Develop Debug Release and RelWithDebInfo

This command is in section 2.4.3 of the manual book.

Below is my error log:

```
Heodel@star:~/HULKsCodeRelease-master$ ./scripts/compile -t simrobot -b Debug
-- Compiling for target simrobot with build type Debug.

[ 1%] Automatic moc for target tuhhSimRobot
[ 1%] Built target tuhhSimRobot_automoc
[ 13%] Built target Vision
[ 32%] Built target Motion
Scanning dependencies of target Brain
[ 33%] Building CXX object src/brain/CMakeFiles/Brain.dir/Knowledge/LandmarkFilter/LandmarkFilter.cpp.o
[ 34%] Building CXX object src/brain/CMakeFiles/Brain.dir/Knowledge/Obstacles/TeamObstacleFilter.cpp.o
[ 35%] Building CXX object src/brain/CMakeFiles/Brain.dir/Knowledge/Obstacles/ObstacleFilter.cpp.o
[ 36%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/CollisionDetection/CollisionDetector.cpp.o
[ 36%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/FootCollisionDetector/FootCollisionDetector.cpp.o
[ 37%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/HeadDamageProvider/HeadDamageProvider.cpp.o
[ 37%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/MotionPlanning/MotionPlanner.cpp.o

/home/heodel/HULKsCodeRelease-master/src/brain/Knowledge/LandmarkFilter/LandmarkFilter.cpp: In member function 'std::tuple<bool, long unsigned int, float> LandmarkFilter::findCenterLineOrientation(const std::vector<LineInfo >&, const LandmarkFilter::PointCluster2D&)':
/home/heodel/HULKsCodeRelease-master/src/brain/Knowledge/LandmarkFilter/LandmarkFilter.cpp:464:45: error: converting to 'std::tuple<bool, long unsigned int, float>' from initializer list would use explicit Constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {bool, long unsigned int&, float&}; <template-parameter-2-2> = void; _Elements = {bool, long unsigned int, float}]'
     Return {true, longestLineId, orientation};
                                             ^
/home/heodel/HULKsCodeRelease-master/src/brain/Knowledge/LandmarkFilter/LandmarkFilter.cpp:466:25: error: converting to 'std::tuple<bool, long unsigned int, float>' from initializer list would use explicit Constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {bool, int, float}; <template-parameter-2-2> = void ; _Elements = {bool, long unsigned int, float}]'
   Return {false, -1, 0.f};
                         ^
[ 38%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/WhistleDetection/WhistleDetection.cpp.o

/home/heodel/HULKsCodeRelease-master/src/brain/Knowledge/LandmarkFilter/LandmarkFilter.cpp: In member function ‘std::tuple<bool, float> LandmarkFilter::findIntersectionOrientation(const LandmarkModel::Intersection&)’:
/home/heodel/HULKsCodeRelease-master/src/brain/Knowledge/LandmarkFilter/LandmarkFilter.cpp:796:38: error: converting to 'std::tuple<bool, float>' from initializer list would use explicit constructor 'constexpr std ::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool&; _U2 = float&; <template-parameter-2-3> = void; _T1 = bool; _T2 = float]'
   Return {hasOrientation, orientation};
                                      ^
[ 39%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/ReplayRecorder/ReplayRecorder.cpp.o
[ 39%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/OdometryOffsetProvider/OdometryOffsetProvider.cpp.o
[ 40% ] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/TeamPlayersAugmenter/TeamPlayersAugmenter.cpp.o
[ 41%] Building CXX object src/brain/CMakeFiles/Brain.dir/SPLNetwork/HULKsMessage.cpp.o
Src/brain/CMakeFiles/Brain.dir/build.make:614: recipe for target 'src/brain/CMakeFiles/Brain.dir/Knowledge/LandmarkFilter/LandmarkFilter.cpp.o' failed
Make[2]: *** [src/brain/CMakeFiles/Brain.dir/Knowledge/LandmarkFilter/LandmarkFilter.cpp.o] Error 1
Make[2]: *** Waiting for unfinished tasks....
CMakeFiles/Makefile2:215: recipe for target 'src/brain/CMakeFiles/Brain.dir/all' failed
Make[1]: *** [src/brain/CMakeFiles/Brain.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
Make: *** [all] Error 2
-- Compilation failed!
```

If you can help me I would be appreciate!

**Comment by rkost** [comment]
Hey @heodel

I do not experience the issue mentioned above on my local system. Therefore it would be great if you could share the log generated by `./scripts/setup simrobot`. This will tell us your compiler version etc.

(Don't worry, running the setup script again will only recreate the `build/simrobot` folder that should not contain a compiled version of our code right now.)

**Comment by Heodel** [comment]
OK Thank you I found that 
> Could NOT find ITTNOTIFY (missing:  ITTNOTIFY_LIBRARY ITTNOTIFY_INCLUDE_DIR) 
Is this very important?
Here are my logs:
```
heodel@star:~/HULKsCodeRelease-master$ ./scripts/setup simrobot
-- Generating files for simrobot.

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiling with GCC
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found JPEG: /usr/local/lib/libjpeg.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.54") 
-- Found FFTW: /usr/lib/x86_64-linux-gnu/libfftw3.so  
-- Could NOT find ITTNOTIFY (missing:  ITTNOTIFY_LIBRARY ITTNOTIFY_INCLUDE_DIR) 
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "3.3") 
-- Include directories: /usr/include;/usr/local/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include/eigen3
-- Link libraries: /usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;-lpthread;/usr/local/lib/libjpeg.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libfftw3.so;dl
-- Found tuhhSDK: /home/heodel/HULKsCodeRelease-master/src/tuhhsdk  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/heodel/HULKsCodeRelease-master/build/simrobot/Debug
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiling with GCC
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found JPEG: /usr/local/lib/libjpeg.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.54") 
-- Found FFTW: /usr/lib/x86_64-linux-gnu/libfftw3.so  
-- Could NOT find ITTNOTIFY (missing:  ITTNOTIFY_LIBRARY ITTNOTIFY_INCLUDE_DIR) 
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "3.3") 
-- Include directories: /usr/include;/usr/local/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include/eigen3
-- Link libraries: /usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;-lpthread;/usr/local/lib/libjpeg.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libfftw3.so;dl
-- Found tuhhSDK: /home/heodel/HULKsCodeRelease-master/src/tuhhsdk  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/heodel/HULKsCodeRelease-master/build/simrobot/Develop
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiling with GCC
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found JPEG: /usr/local/lib/libjpeg.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.54") 
-- Found FFTW: /usr/lib/x86_64-linux-gnu/libfftw3.so  
-- Could NOT find ITTNOTIFY (missing:  ITTNOTIFY_LIBRARY ITTNOTIFY_INCLUDE_DIR) 
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "3.3") 
-- Include directories: /usr/include;/usr/local/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include/eigen3
-- Link libraries: /usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;-lpthread;/usr/local/lib/libjpeg.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libfftw3.so;dl
-- Found tuhhSDK: /home/heodel/HULKsCodeRelease-master/src/tuhhsdk  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/heodel/HULKsCodeRelease-master/build/simrobot/Release
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiling with GCC
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found JPEG: /usr/local/lib/libjpeg.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.54") 
-- Found FFTW: /usr/lib/x86_64-linux-gnu/libfftw3.so  
-- Could NOT find ITTNOTIFY (missing:  ITTNOTIFY_LIBRARY ITTNOTIFY_INCLUDE_DIR) 
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "3.3") 
-- Include directories: /usr/include;/usr/local/include;/usr/include;/usr/include;/usr/include;/usr/include;/usr/include/eigen3
-- Link libraries: /usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;-lpthread;/usr/local/lib/libjpeg.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libfftw3.so;dl
-- Found tuhhSDK: /home/heodel/HULKsCodeRelease-master/src/tuhhsdk  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/heodel/HULKsCodeRelease-master/build/simrobot/RelWithDebInfo
```

**Comment by Heodel** [comment]
Dear:
I think this error is related to GCC and -The C compile is GNU 5.4.0, The CXX compile is GNU 5.4.0 version number?
Can you provide your operating system version number and compiler version number?
Thank you very much

**Comment by rkost** [comment]
> Could NOT find ITTNOTIFY (missing: ITTNOTIFY_LIBRARY ITTNOTIFY_INCLUDE_DIR)

So no, this is not important for now.

Your GCC compiler seems quite out of date. You may want to retry with at least version 6. I am currently running arch linux with GCC 8.2.1 and it works just fine. Having gcc 6 should also work though.

**Comment by Heodel** [comment]
Thank you very much, I have successfully compiled the RelWithDebInfo version. After I uploaded the robot software, the robot restarted. After I connected to SSH, I found that the hulk service was enabled, but when I studied B-Human, the robot was this time. Stateful, actionable. But HULK's service is on, my Nao robot has no action, can you tell me how can I get the robot to move?

Then for the mate of the tool I encountered the following error in python3, always showing trying to connect localhost or robots ip.
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    Self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    Self._target(*self._args, **self._kwargs)
  File "/home/heodel/HULKsCodeRelease-master/tools/mate/mate/net/nao.py", line 41, in <lambda>
    Self.config_thread = threading.Thread(target=lambda: asyncio.new_event_loop().run_until_complete(self.__connect_config()))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    Return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    Raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    Result = coro.send(None)
  File "/home/heodel/HULKsCodeRelease-master/tools/mate/mate/net/nao.py", line 64, in __connect_config
    Self.config_loop = asyncio.get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 632, in get_event_loop
    Return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 578, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-4'.

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    Self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    Self._target(*self._args, **self._kwargs)
  File "/home/heodel/HULKsCodeRelease-master/tools/mate/mate/net/nao.py", line 39, in <lambda>
    Self.debug_thread = threading.Thread(target=lambda: asyncio.new_event_loop().run_until_complete(self.__connect_debug()))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    Return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    Raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    Result = coro.send(None)
  File "/home/heodel/HULKsCodeRelease-master/tools/mate/mate/net/nao.py", line 45, in __connect_debug
    Self.debug_loop = asyncio.get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 632, in get_event_loop
    Return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 578, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-3'.

```
I encountered some minor errors in your official code during the installation process:
In section 2.5.1 of the manual
```
Listing 2.5.1
Ln -s sysroot-7.3.0-1.tar.bz2 toolchain /sysroot-7.3.0-1.tar.bz2
./ scripts/gammaray -w -a <NAOIP > <NAONUMBER >
```
After the ln command is executed, when I execute the gammaray command, I always get an error. When I look at the code, I find 153 lines in gammaray:
```
  If [ ! -f "${BASEDIR}/toolchain/sysroot.tar.bz2" ]; then
```
So the command executed in 2.5.1 should be
```
Ln -s sysroot-7.3.0-1.tar.bz2 toolchain /sysroot.tar.bz2
```
Not is
```
Ln -s sysroot-7.3.0-1.tar.bz2 toolchain /sysroot-7.3.0-1.tar.bz2
```
If you can help me thank you very much.

**Comment by rkost** [comment]
Hey @Heodel,

I created #5, #6, #7 from your problems mentioned above. Please note that you should create new issues when encountering new problems rather than switching to completely other problems that have nothing to do with the title / original problem. This way other teams profit from your issues and can find them easier.

I will close this issue as it is fixed for now and try to help you in the corresponding new ones.
